index:
    path: /
    controller: App\Controller\HomeController::home

produits:
    path: /produits
    controller : App\Controller\HomeController::produits

actualite:
    path: /actualite
    controller : App\Controller\HomeController::actualite

histoire:
    path: /histoire
    controller : App\Controller\HomeController::histoire

contact:
    path: /contact/new
    controller : App\Controller\HomeController::contact

app_login:
    path: /login
    controller : App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller : App\Controller\SecurityController::logout

app_register:
    path: /register
    controller : App\Controller\RegistrationController::register

panier:
    path: /panier
    controller: App\Controller\HomeController::panier

espaceperso:
    path: /espaceperso
    controller: App\Controller\EspacepersoController::index

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index